#pragma once
#include <string>

// The bundled per-achievement tier-points table (data/achievement_points.json, generated by
// builder/build_achievement_points.py). Loaded once at AddonLoad; lets AccountData compute an account's total
// achievement points offline (tier points vs /v2/account/achievements progress) instead of bulk-fetching ~4k
// achievement definitions at runtime. Daily/Weekly/Monthly achievements are NOT in the table -- their AP is the
// account's capped daily_ap/monthly_ap, added separately. See builder/docs/api-client.md.
namespace AchPoints
{
    void Load(const std::string& path);   // parse the bundled JSON (idempotent; a no-op if the file is absent)
    bool Loaded();

    // AP earned for one /v2/account/achievements row. id not in the table (daily/monthly/unknown) -> 0.
    //   base = (done ? all tier points : sum of tier points whose count <= current).
    //   repeatable -> min(point_cap, perCycle*repeated + (done ? 0 : base))  -- a done cycle is already in `repeated`.
    int PointsFor(int id, int current, int repeated, bool done);
}
